export const packages = [
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon6.png",
    title: "Best Seller",
    subtitle: "Smart Design Solution",
    features: [
      "2 Logo Design Concepts",
      "5 Revisions (Additional $10)",
      "2 Dedicated Designers",
      "24 To 48 Hours TAT",
      "Final Files (PNG,JPG)",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership Rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "39",
    oldPrice: "195",
    discount: "80",
    orderLink: "#",
    tag: "Popular",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "The Ultimate",
    subtitle: "Cutting-Edge Design",
    features: [
      "4 Logo Design Concepts",
      "Unlimited Revisions",
      "3 Dedicated Designers",
      "Business Card Design",
      "Brand Icon / Fav Icon",
      "24 To 48 Hours TAT",
      "Final Files(JPG,PNG)",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "68",
    oldPrice: "340",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon3.png",
    title: "Business Plus",
    subtitle: "Ideal design solutions",
    features: [
      "6 Logo Design Concepts",
      "Unlimited Revisions",
      "4 Dedicated Designers",
      "stationery Design",
      "Brand Icon / Fav Icon",
      "24 To 48 Hours TAT",
      "Final Files",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership Rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "119",
    oldPrice: "595",
    discount: "80",
    orderLink: "#",
    tag: "TOP RATED",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon2.png",
    title: "Enterprise",
    subtitle: "Perfect design solution",
    features: [
      "unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "6 Dedicated Designers",
      "stationery Design",
      "Corporate Brochure",
      "Social Media Designs",
      "Brand Icon / Fav Icon",
      "24 To 48 Hours TAT",
      "Final Files",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership Rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "119",
    oldPrice: "745",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "Enterprise Plus",
    subtitle: "Value added design solution",
    features: [
      "unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "8 Dedicated Designers",
      "1 Pages Custom Web Design",
      "Complete stationery Design",
      "Corporate Brochure",
      "Social Media Designs",
      "24 To 48 Hours TAT",
      "Final Files",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership Rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "349",
    oldPrice: "1245",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "The Corporate",
    subtitle: "Complete design solution",
    features: [
      "Website Design & Development",
      "unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "2 Teams",
      "Dedicated Account Manager (Sr Developer)",
      "Complete stationery Design",
      "Corporate Brochure",
      "Social Media Designs",
      "Mobile Responsive Website",
      "Social Media Integration",
      "24 Hours To 5 Days TAT",
      "Final Files",
      "100% Real Account Manager (No Bot)",
      "100% Custom Design (No Templates)",
      "100% Ownership Rights",
      "100% Assurance Guarantee",
      "100% Money Back Guarantee",
      "24/7 Customer Support",
    ],
    price: "499",
    oldPrice: "1745",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon6.png",
    title: "Illustrative Starter",
    subtitle: "Illustrative/Mascot Logo",
    features: [
      "3 Custom Logo Design Concepts",
      "Unlimited Revisions",
      "By 2 Designers",
      "48 To 72 Hours TAT",
      "All Final Files Format (AI,PSD,EPS,PNG,GIF,JPG,PDF)",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
    price: "119",
    oldPrice: "995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon5.png",
    title: "Illustrative Budget",
    subtitle: "Illustrative/Mascot Logo",
    features: [
      "4 Custom Logo Designer",
      "By 3 Designers",
      "48 To 72 Hours TAT",
      "UNLIMITED Revisions",
      "All Final Files Format (AL,PSD,EPS,PNG,GIF,JPG,PDF)",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
    price: "299",
    oldPrice: "1495",
    discount: "80",
    orderLink: "#",
    tag: "Popular",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Illustrative Ultimate",
    subtitle: "Illustrative/Mascot Logo",
    features: [
      "UNLIMITED Logo Design Concepts",
      "By 4 Designers",
      "24 To 48 Hours TAT",
      "UNLIMITED Revisions",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
    price: "399",
    oldPrice: "1995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Logo",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "3D Special ",
    subtitle: "Perspective Brand Identity",
    features: [
      "3 Unique 3D Logo Concept",
      "Light Effects And VFX",
      "Fully Rendered",
      "Multiple 3D Angles",
      "By 4 Award Winning Designers",
      "48 To 72 Hours TAT",
      "UNLIMITED Revisions",
      "All Files Formats Included",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
    price: "499",
    oldPrice: "2245",
    discount: "80",
    orderLink: "#",
    tag: "TOP RATED",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon3.png",
    title: "Budget",
    subtitle: "Hassle Free Design",
    features: [
      "3 Page Customize Website",
      "1 Design Concept",
      "1 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Turn Around 5 Business Days",
      "3 Stock Photos",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
      "24/7 Chat Support",
    ],
    price: "199",
    oldPrice: "995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon2.png",
    title: "Best Seller",
    subtitle: "Hassle Free Design",
    features: [
      "Up to 5 Page Customize Website",
      "1 Design Concept",
      "1 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Turn Around 5 Business Days",
      "5 Stock Photos",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
      "24/7 Chat Support",
    ],
    price: "599",
    oldPrice: "2995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon5.png",
    title: "The Ultimate",
    subtitle: "Smart Design Solution",
    features: [
      "Up TO 8 Page Customize Website",
      "2 Design Concept",
      "1 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Free On-Page SEO",
      "Turn Around 5 Business Days",
      "7 Stock Photos",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
      "24/7 Chat Support",
    ],
    price: "899",
    oldPrice: "4495",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon6.png",
    title: "Business Plus",
    subtitle: "Ideal Design Solution",
    features: [
      "Up To 10 Page Customize Website",
      "2 Design Concept",
      "2 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Free CMS Integrated",
      "Turn Around 7 Business Days",
      "8 Stock Photos",
      "SEO Friendly",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
    ],
    price: "999",
    oldPrice: "4995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "Enterprise",
    subtitle: "Perfect Design Solution",
    features: [
      "Up To 10 Page Customize Website",
      "2 Design Concept",
      "2 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Free 1 Year Web Hosting",
      "Free CMS Integrated",
      "Free On-Page SEO",
      "Free 1 Banner",
      "Turn Around 7 Business Days",
      "10 Stock Photos",
      "SEO Friendly",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
    ],
    price: "1399",
    oldPrice: "6995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Enterprise Plus",
    subtitle: "Complete Design Solution",
    features: [
      "Unlimited Website Pages",
      "2 Design Concept",
      "2 Dedicated Design Team",
      "Complete Deployment",
      "Mobile Responsive Design",
      "Free 1 Year Web Hosting",
      "Free CMS Integrated",
      "Free On-Page SEO",
      "Free 1 Banner",
      "Free 15 Emails",
      "Business Card Design",
      "Turn Around 7 Business Days",
      "12 Stock Photos",
      "SEO Friendly",
      "Payment Integration Gateway",
      "Social Media Design",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Dedicate Account Manager",
    ],
    price: "1999",
    oldPrice: "9995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Startup E-Commerce Package",
    subtitle: "",
    features: [
      "Cusomized Design",
      "30 Products uploads",
      "Content Management System (CMS)",
      "Mini Shopping Cart Integration",
      "Easy Product Search",
      "Dedicated designer & developer",
      "Unlimited Revision",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
    price: "499",
    oldPrice: "999",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Professional E-Commerce Package",
    subtitle: "Best Seller",
    features: [
      "60 Products",
      "10 Stock Images",
      "2 jQuery Slider Banner",
      "3 Banner Design",
      "Contact/Query Form",
      "Social Media Integration (Facebook, Instagram, LinkedIn)",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Complete Deployment",
      "Mobile Responsive",
      "FREE Google Friendly Sitemap",
      "100% Ownership Rights",
      "100% Satisfaction Guaranteed",
      "100% Unique Design Guaranteed"
    ],
    price: "999",
    oldPrice: "1899",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Website",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Elite  E-Commerce Package",
    subtitle: "Best Seller",
    features: [
      "100 Products",
      "10 Stock Images",
      "2 jQuery Slider Banner",
      "3 Banner Design",
      "UNLIMITED Logo Design Concepts",
      "By 6 Award Winning Designers",
      "Icon Design",
      "UNLIMITED Revisions",
      "Print Media",
      "Stationary Design(BusinessCard, Letterhead & Envelope)",
      "Invoice Design, Email Signature",
      "Bi - Fold Brochure(OR) 2 Sided Flyer Design",
      "Product Catalog Design",
      "Sign age Design(OR) Label Design",
      "T - Shirt Design(OR) Car Wrap Design",
      "Contact / Query Form",
      "Social Media Handles Creation(Facebook, Instagram, LinkedIn)",
      "Signup Area",
      "Search Bar",
      "Custom Coding & Development",
      "SEO - friendly coding(Meta - tags)",
      "Fast Load Time",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Complete Deployment",
      "Mobile Responsive",
      "FREE Google Friendly Sitemap",
      "100 % Ownership Rights",
      "100 % Satisfaction Guaranteed",
      "100 % Unique Design Guaranteed",


    ],
    price: "1999",
    oldPrice: "3999",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Video Animation",
    icon: "/images/Packages/PackagesIcon2.png",
    title: "Typography",
    subtitle: "Hassle Free Design Solution Recommended For Profesionals",
    features: [
      "30 Second Video",
      "Professional Script",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "2 Weeks Delivery",
      "Unlimited Revisions",
    ],
    price: "299",
    oldPrice: "1495",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Video Animation",
    icon: "/images/Packages/PackagesIcon1.png",
    title: "Motion Graphics",
    subtitle: "Smart Design Solution Recommended For Small Scale Businesses",
    features: [
      "30 Second Video",
      "Professional Script",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "2 Weeks Delivery",
      "Unlimited Revisions",
    ],
    price: "399",
    oldPrice: "1995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Video Animation",
    icon: "/images/Packages/PackagesIcon4.png",
    title: "Explainer Videos",
    subtitle: "Suitable For Small Looking For a Custom Logo.",
    features: [
      "30 Second Video",
      "Professional Script",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "2 Weeks Delivery",
      "Unlimited Revisions",
    ],
    price: "599",
    oldPrice: "2995",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
  {
    type: "Video Animation",
    icon: "/images/Packages/PackagesIcon6.png",
    title: "Whiteboard",
    subtitle: "Hassle Free Design Solution Recommended For Professionals",
    features: [
      "60 Second Video",
      "Professional Script",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "2 Weeks Delivery",
      "Unlimited Revisions",
    ],
    price: "850",
    oldPrice: "4250",
    discount: "80",
    orderLink: "#",
    tag: "",
  },
];