export const LogoDesignServicesList = [
  {
    number: "01",
    title: "Quality Service Guaranteed",
    desc: " At Design Alligators, we understand your brand is unique and deserves a logo that sets it apart from the competition. That's why our Expert Logo Designers are dedicated to bringing your vision to life, and transforming your ideas into stunning logos that leave a lasting impression.",
    img: "logoDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "The Creative Process",
    desc: "Our Logo Design Services process involves four phases: research, ideation, execution, and evolution. This approach ensures that every aspect of your brand is considered and incorporated into the final design, resulting in a logo that truly represents your vision and values.",
    img: "logoDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Logo Redesigning Service",
    desc: "If you already have a logo, our Expert Logo Designers can help you update it to better reflect your current brand identity. We'll work with you to understand your goals and make tweaks to your existing logo to ensure it aligns with your brand message.",
    img: "logoDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Logo Designing Software",
    desc: "  At our Logo Design Company, we use the latest software tools and technologies to create stunning logos that are both aesthetically pleasing and functional. Our designers are proficient in industry-standard software such as Adobe Illustrator, Sketch, and CorelDRAW, enabling us to create logos in a variety of formats that are optimized for print and digital media.",
    img: "logoDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const brandingServicesList = [
  {
    number: "01",
    title: "Brand. Design. Strategy.",
    desc: "  At Design Alligators, branding is not just about having a logo or a website. It's about creating a brand identity that reflects who you are and what you stand for.",
    img: "branding/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Website Redesign Service",
    desc: " We understand that your website is your customers' first point of contact, and first impressions are essential. That's why we offer website redesign services to help you stand out.",
    img: "branding/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Logo Design Services",
    desc: "Your logo is the face of your brand and the first thing your customers will notice. Our logo design services are designed to help you create a unique and memorable logo that reflects your brand identity.",
    img: "branding/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Visual Design Services",
    desc: "  We provide attractive visual design services that help you communicate your brand identity effectively. Our visual design services include brand voice, social media, and other design components that make your brand stand out.",
    img: "branding/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const webDesignServicesList = [
  {
    number: "01",
    title: "Website Design Visual Bits",
    desc: "We understand that a website is often the first impression potential customers have of your business. That's why we work closely with you to ensure that your website represents your brand and values while being user-friendly and visually appealing.",
    img: "UI-UXDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Website Design Cloud Access",
    desc: "At Design Alligators, a website design is about aesthetics and enhancing your website's functionality and performance. Our Website Design Cloud Access service is a perfect blend of both. With this service, you get an attractive website design and cloud access to track various actions such as leads, calls, and purchase records.",
    img: "UI-UXDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Website Design Technical Assistance",
    desc: "Our team of experts is available around the clock to provide responsive and reliable technical support. As the best Website Design Company in the United States, we pride ourselves on being there for our clients whenever they need us. Whether your system has crashed or you're facing other issues, our experienced faculty can help you out of any inconvenience.",
    img: "UI-UXDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Website Design 24/7 Support System",
    desc: "Design Alligators provides the best support system for Website Design in the United States. Our 24/7 support team is always available to guide you through your Website Design journey. And if you have any questions or concerns, we have various communication.",
    img: "UI-UXDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const animationServicesList = [
  {
    number: "01",
    title: "Video Animation Production",
    desc: " We know that a professionally animated film can change the game. That's why we're the only ones you need to contact for a full-service, end-to-end video animation production, from concept to screenplay to animation to post-production.",
    img: "VideoAnimation/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Undivided Focus on Animations",
    desc: "Unlike other companies that spread themselves thin with various services, we focus solely on video animations. This approach allows us to provide the highest customer experience possible, and it shows in our work.",
    img: "VideoAnimation/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Creative Video Animations",
    desc: " We specialize in creating custom creative video animations that help businesses grow their user base. Our years of experience and proven track record of success have earned us a lot of referral business.",
    img: "VideoAnimation/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Expert Video Animation",
    desc: "If you're looking for a professional and experienced Video Animation Company in the USA, look no further than Design Alligators. Our mission is to provide high-quality Video Animation Services at an affordable price.",
    img: "VideoAnimation/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const mobileAppDesignServicesList = [
  {
    number: "01",
    title: "Design Strategy to Development",
    desc: "We offer a full range of Mobile Application Design Services, from UI/UX design to project management, testing, deployment, and support. No matter what stage of development your app is in, we can help take it to the next level.",
    img: "mobileAppDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "High Quality Services",
    desc: "At Design Alligators, we believe in taking a personal approach to mobile app design. We know that every business is different, so we take the time to listen carefully to your needs and ideas before developing a thorough understanding of your business objectives.",
    img: "mobileAppDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Responsive Design for Mobile Devices",
    desc: " At Design Alligators, we understand that more and more people are accessing the internet through mobile devices. That's why we take responsive design seriously. We ensure that our mobile applications are designed to be responsive across various devices, from smartphones to tablets.",
    img: "mobileAppDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Expertise in Different Platforms",
    desc: "At Design Alligators, our experienced Mobile Application Designers and Mobile Application Developers have expertise in various mobile app platforms and technologies. Whether you're looking to develop an app for iOS or Android or interested in hybrid app development, we've got you covered.",
    img: "mobileAppDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const WebDevServicesList = [
  {
    number: "01",
    title: "Creative Website Development",
    desc: " At our Website Development Company, a website is like an alligator - it needs to be strong, powerful, and adaptable. We provide Web Development Solutions to help your business thrive in today's fast-paced online world.",
    img: "WebDev/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Custom Website Development",
    desc: "We understand your website is your digital storefront, and the first impression is everything. That's why our team of alligator-like developers provides exceptional and tailored web development services that cater to all your needs.",
    img: "WebDev/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Website Dreams into Reality",
    desc: "We understand that a website is not just a collection of pages and images but it's an online representation of your business. That's why we take a personalized approach to create a website that truly reflects your brand's values and vision.",
    img: "WebDev/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Robust E-commerce Solutions",
    desc: "In today's digital age, having a strong online presence is crucial for any business to thrive. At Design Alligators, we specialize in providing robust e-commerce solutions to help businesses sell their products and services online.",
    img: "WebDev/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const webRedesignServicesList = [
  {
    number: "01",
    title: "Website Redesign Assessment",
    desc: "We start by assessing your current website and identifying areas that need improvement. Our team of experts examines everything from website speed to user experience to ensure your new website performs at its best.",
    img: "webReDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Custom Redesign Service",
    desc: "Our team of UX and UI designers work collaboratively with you to create a custom design that aligns with your brand and meets your business objectives. We focus on creating a user-friendly design that is easy to navigate and encourages user engagement.",
    img: "webReDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Web Development Service",
    desc: " Our Website Redesign Developers work on both the front-end and back-end of your website to create a seamless and responsive user experience. We use the latest web development technologies and follow best practices to ensure your website is secure and optimized for search engines.",
    img: "webReDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Testing and Launch",
    desc: "We put your website through rigorous testing to ensure it is free of bugs and performs as intended. Once testing is complete, we launch your website and provide ongoing technical support to ensure it continues to run smoothly.",
    img: "webReDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const WebAppDevServicesList = [
  {
    number: "01",
    title: "App Quality Assurance",
    desc: "We take our Quality Management System seriously, and our team follows the Integrated Manual and Automated Testing (IMATT) approach to ensure that your Web App is secure, fast, and sustainable.",
    img: "WebAppDev/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Web Application Integration",
    desc: "We offer seamless Web Application integration with your CMS and software framework through custom APIs. Our expert Web Application Developers use the latest CI/CD work line to make changes to your software without disrupting your workflow.",
    img: "WebAppDev/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Optimization and Evolution",
    desc: "There is always room for improvement and evolution to meet your business's and users' ever-changing needs. Our team of Web Application Developers is committed to optimizing and enhancing your Web App through continuous improvements and DevOps practices.",
    img: "WebAppDev/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "App Technical Assistance",
    desc: "At Design Alligators, we have a talented team of Web Application Developers who are always ready to provide exceptional technical assistance. As a Web Application Development Agency in Brooklyn, Chicago, and Edison, we understand the importance of maintaining a functional website.",
    img: "WebAppDev/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const hostingServicesList = [
  {
    number: "01",
    title: "Unlimited Web Hosting Bandwidth",
    desc: " No more worrying about not having enough space for your online needs – we provide an abundance of web hosting services to make sure you get everything you need. With our shared, VPS and dedicated server solutions, the sky's the limit when it comes to creating a unique website experience!",
    img: "webHosting/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Business Emails in Web Hosting",
    desc: "Your brand deserves premium Website Hosting and professional email addresses. That's why we offer superior services tailored to the needs of SMBs, featuring business emails alongside our top-notch hosting solutions!",
    img: "webHosting/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Hosting Services with Free SSL",
    desc: "At our Web Hosting Company, we guarantee a secure and encrypted connection between your website and your customers' browsers. With our SSL certificates, your customers can have the peace of mind they need before making a transaction.",
    img: "webHosting/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Monthly Backup in Web Hosting",
    desc: "At our Web Hosting Company, we guarantee a secure and encrypted connection between your website and your customers' browsers. With our SSL certificates, your customers can have the peace of mind they need before making a transaction.",
    img: "webHosting/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const ecommerceServicesList = [
  {
    number: "01",
    title: "Website Domain and Hosting",
    desc: "Choosing a domain name for your company shouldn't be based on the fact that it will serve as its sole internet address, it's just so much more than that. That's why we take great care to find a domain name that aptly describes your business and makes it stand out from the competition.",
    img: "EcommerceSolution/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Ecommerce Website Order Management",
    desc: "See your eCommerce dreams come to life with us! Our experienced team will take care of every step needed - from gathering orders, processing returns and delivering packages. With our award-winning solutions in the USA you'll have a successful online store up and running before you know it.",
    img: "EcommerceSolution/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Ecommerce Website Customer Support",
    desc: "At Design Alligators, we understand how essential friendly customer support is for any eCommerce business to prosper. That's why we strive to provide extraordinary Ecommerce Website Solutions throughout the USA with a focus on making sure our customers are completely satisfied!",
    img: "EcommerceSolution/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Website Technical Assistance",
    desc: " At Design Alligators, we're experts in crafting eCommerce experiences that perform like a dream. Our team of experienced professionals are leading the way for USA businesses to reach their fullest potential with our comprehensive Ecommerce Website Solutions!.",
    img: "EcommerceSolution/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const mobileAppServicesList = [
  {
    number: "01",
    title: "Mobile App Development",
    desc: " Whether you require Android App Development Services or IOS App Development Strategies, we've got you covered. We use the most recent versions of these platforms to ensure that your Mobile App is optimized for the best possible user experience.",
    img: "mobileAppDevelopment/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Expert Development Team",
    desc: "At Design Alligators, we take pride in our team of expert Mobile App Developers dedicated to delivering the best possible Mobile Application Development Services. Our team has years of experience developing Mobile Apps across various platforms and industries.",
    img: "mobileAppDevelopment/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Affordable Development Solutions",
    desc: " We understand that Mobile App Development can be expensive, so we offer affordable Mobile Application Development Services tailored to meet your budget requirements. Our team works with you to understand your needs and develop a cost-effective solution.",
    img: "mobileAppDevelopment/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "What Client Say",
    desc: "Design Alligators is a well-known Mobile Application Development Company in New York, Chicago and Edison. We have happy and satisfied customers. Their satisfaction is our success. Innovative procedures and techniques are also important in completing tasks more quickly.",
    img: "mobileAppDevelopment/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const SEOServicesList = [
  {
    number: "01",
    title: "Experienced SEO Agency",
    desc: "  We have the experience and expertise to help your business achieve its goals. Our team of SEO experts stays up-to-date with the latest trends and techniques to ensure that your website ranks high on search engine results pages.",
    img: "SEO/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Customized SEO Services",
    desc: " Every business is unique, so we offer customized SEO Services tailored to your needs and requirements. Our SEO experts work closely with you to develop a customized SEO strategy to drive targeted website traffic.",
    img: "SEO/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Monthly SEO Reporting",
    desc: " We believe in transparency and provide monthly SEO reporting to keep you up-to-date on your website's performance. Our detailed reports provide valuable insights into your website's traffic, rankings, and overall performance, allowing you to make informed decisions.",
    img: "SEO/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Affordable SEO Services",
    desc: "We offer affordable SEO Services in USA to help businesses of all sizes achieve their SEO goals without breaking the bank. Our SEO Services are designed to maximize your investment's value, helping you achieve long-term success.",
    img: "SEO/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const SSMServicesList = [
  {
    number: "01",
    title: "Social Media Ad Boost ",
    desc: " Our SMM Experts manage all the Social Media Marketing Ad Campaigns effectively. It boosts your related posts on multiple Social Media platforms to bring new customers on board. The advertised post must be attractive to the intended viewers.",
    img: "SSM/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Affordable SM Packages",
    desc: "We offer the Best and most Affordable Social Media Marketing Packages. We value our customers and tend to accomplish their business needs. We have a variety of packages valued differently which are very suitable yet cost-effective for you.",
    img: "SSM/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "SMM Customer Support",
    desc: " At Design Alligators, we value our customers and their concerns. That is why we make our support accessible to you at all times. If you have any queries, you can reach us and get immediate consultation.",
    img: "SSM/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Examine Follower Growth",
    desc: "The growth in followers is the most obvious way to analyze your audience's behavior. An Increasing rate of followers of Social Media handles confirms the accuracy of the Social Media Marketing Campaign. Get Professional Social Media Marketing Services in the USA.",
    img: "SSM/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const PPCServicesList = [
  {
    number: "01",
    title: "Experienced PPC Agency",
    desc: " As a leading PPC Agency in United States, we have the experience and expertise to help your business achieve its advertising goals. Our team of PPC experts stays up-to-date with the latest trends and techniques to ensure your campaigns are optimized.",
    img: "PPC/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Customized PPC Services",
    desc: "Every business is unique, so we offer customized PPC Services tailored to your specific needs and requirements. Our PPC experts work closely with you to develop a customized PPC strategy to drive targeted website traffic and generate more leads and sales.",
    img: "PPC/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Monthly PPC Reporting",
    desc: " We believe in transparency and provide monthly PPC reporting to keep you up-to-date on your campaigns' performance. Our detailed reports provide valuable insights into your campaigns' impressions, clicks, conversions, and overall performance.",
    img: "PPC/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Affordable PPC Services",
    desc: "We offer affordable PPC Services in United States to help businesses of all sizes achieve their advertising goals without breaking the bank. Our PPC Services are designed to maximize your investment's value, helping you achieve long-term success.",
    img: "PPC/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const emailServicesList = [
  {
    number: "01",
    title: "Expert Email Marketing Team",
    desc: "We have a team of experienced professionals who can help you create effective Email Marketing Campaigns that resonate with your target audience. We stay up-to-date with the latest email marketing trends and best practices to ensure your campaigns deliver maximum results.",
    img: "EmailMarketing/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Customized Email Marketing Services",
    desc: " Every business has unique needs, so we offer customized email marketing solutions tailored to your goals and requirements. Our team of experts will work closely with you to develop an Email Marketing Strategy designed to engage your audience and drive conversions.",
    img: "EmailMarketing/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Detailed Reporting & Analytics",
    desc: " We believe in transparency and provide detailed reporting and analytics to help you measure the effectiveness of your email marketing campaigns. Our reports provide valuable insights into your Email Marketing Campaigns' open, click-through, and conversion rates.",
    img: "EmailMarketing/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Affordable Email Marketing Agency",
    desc: "We offer affordable Email Marketing Services in United States that are designed to provide maximum value for your investment. Our pricing is transparent, and we never charge hidden fees. With our Email Marketing Services, you can achieve your goals without breaking the bank.",
    img: "EmailMarketing/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const ecommerceMarketingServicesList = [
  {
    number: "01",
    title: "Expert Ecommerce Marketing",
    desc: "Our eCommerce Marketing Firm has a team of experienced professionals who create effective eCommerce Marketing strategies. We stay up-to-date with the latest eCommerce Marketing trends and best practices to ensure your campaigns deliver maximum results.",
    img: "EcommerceMarketing/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Customized Marketing Solutions",
    desc: " Every eCommerce business is unique, so we offer customized eCommerce Marketing Solutions tailored to your specific goals and requirements. Our team of eCommerce Marketing Experts will work closely with you to develop an eCommerce Marketing Strategy.",
    img: "EcommerceMarketing/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Reporting and Analytics",
    desc: "  We believe in transparency and provide detailed reporting and analytics to help you measure the effectiveness of your eCommerce Marketing Campaigns. Our reports provide valuable insights into your campaigns' performance.",
    img: "EcommerceMarketing/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Affordable Ecommerce Marketing",
    desc: "Our eCommerce Marketing Services are affordable and designed to maximize your investment's value. We offer transparent pricing and never charge hidden fees. With our eCommerce Marketing Services, you can achieve your business goals without breaking the bank.",
    img: "EcommerceMarketing/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const tshirtServicesList = [
  {
    number: "01",
    title: "Custom T-Shirt Design",
    desc: "At Design Alligators, we offer a wide range of custom T-shirt Design options that allow you to personalize your T-shirts to your brand, logo, or message whether you need shirts for a company event, a sports team, or a family reunion.",
    img: "TShirtDesigning/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Professional T-Shirt Designers",
    desc: " Our team of graphic designers can help you create a unique design tailored to your needs. We work with you to develop a design that will stand out and grab attention while still staying true to your brand and message.",
    img: "TShirtDesigning/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Multiple Printing Options",
    desc: "  We offer various printing options to fit your specific needs, including screen printing, direct-to-garment printing, and embroidery. Our team will work with you to determine the best printing method for your project based on design, quantity, and budget.",
    img: "TShirtDesigning/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Strict Quality Control",
    desc: " We take pride in our commitment to quality control. Every shirt we print undergoes a thorough inspection to ensure it meets our high standards. This means you can be confident that your shirts will look great and last for years.",
    img: "TShirtDesigning/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const invitationServicesList = [
  {
    number: "01",
    title: "Invitation Card Designing",
    desc: "Our team of skilled Invitation Card Designers will work with you to bring your unique vision to life and create an invitation that perfectly captures the essence of your event. Whether it's a wedding, corporate event, or birthday party, we offer a wide range of personalized options so that you can create the perfect invitation for your occasion.",
    img: "InvitationCard/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Lightning-Fast Delivery",
    desc: " That's why we specialize in lightning-fast delivery and only take an order if we are certain we can deliver it on time. Our commitment to fast and reliable Invitation Card Design Service means that you can focus on what matters most – enjoying your event.",
    img: "InvitationCard/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Unbeatable Pricing",
    desc: "High-quality Invitation Card Design shouldn't come at a premium price. That's why we provide affordable Invitation Card Design Services that maintain quality. Our team of talented Invitation Card Designers will work with you to create an invitation that meets your unique needs and fits within your budget.",
    img: "InvitationCard/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Design Review & Revisions",
    desc: " We understand the importance of quality Invitation Card Design, which is why we go above and beyond to ensure that every invitation we produce is of the highest standard. You can trust us to deliver an invitation that looks great and functions flawlessly, setting the tone.",
    img: "InvitationCard/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const flyerServicesList = [
  {
    number: "01",
    title: "Creative Custom Flyer Design",
    desc: "  We understand that every business is unique, and that's why we offer a wide range of Custom Flyer Design options for your flyer. Our team of Flyer Designers will work with you to create a Flyer Design that fits your brand's identity and messaging, while also grabbing your target audience's attention.",
    img: "FlyerDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Creative Concept Development",
    desc: " Our graphic designers will work with you to develop a creative concept that effectively communicates your message. We'll bring your ideas to life, creating a flyer design that will leave a lasting impression on your audience and set you apart from your competitors.",
    img: "FlyerDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Easy Printing Options",
    desc: " We offer various printing options to fit your needs, including digital printing, offset printing, and large-format printing. Our Flyer Design Team will work with you to determine the best printing method for your project based on design, quantity, and budget.",
    img: "FlyerDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Fast Turnaround Time",
    desc: " We understand that time is of the essence when it comes to promoting your business or event. That's why we specialize in lightning-fast delivery and only take an order if we are certain we can deliver it on time. Our commitment to fast and reliable Flyer Design Service means that you can focus on what matters most – growing your business.",
    img: "FlyerDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const brochureServicesList = [
  {
    number: "01",
    title: "Creative Custom Design",
    desc: "  We understand that every business has a unique story to tell, so we offer custom design options for your brochure. Our Brochure Designers will work with you to create a brochure design that accurately represents your brand and messaging while grabbing your target audience's attention.",
    img: "BrochureDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Best Concept Development",
    desc: "   Our Graphic Designers will work with you to develop a creative concept that effectively communicates your message. We'll bring your ideas to life, creating a brochure design that will leave a lasting impression on your audience and set you apart from your competitors.",
    img: "BrochureDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Effective Content Development",
    desc: " We understand that your brochure's content is as important as its design. That's why we offer content development services, including copywriting and editing, to ensure your message is clear, concise, and impactful.",
    img: "BrochureDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Multiple Printing Options",
    desc: "We offer various printing options to fit your needs, including digital printing, offset printing, and large-format printing. Our Brochure Design team will work with you to determine the best printing method for your project based on design, quantity, and budget.",
    img: "BrochureDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];
export const catalogueServicesList = [
  {
    number: "01",
    title: "Custom Design",
    desc: " Our professional Catalogue Designers will work with you to create a custom catalogue design that accurately represents your brand and messaging. We understand that every business has its unique story to tell, and we ensure that your design captures the essence of your business and stands out from the competition.",
    img: "CatalogueDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Creative Development",
    desc: " Our Graphic Designers are experts at developing creative concepts that communicate your message effectively. We bring your ideas to life with stunning visuals and design elements that will make your catalogue memorable.",
    img: "CatalogueDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Content Development",
    desc: " We understand that compelling content is just as important as beautiful design, so we offer content development services such as copywriting and editing. Our experienced writers will help you craft a message that resonates with your audience and inspires them to take action.",
    img: "CatalogueDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Printing Options",
    desc: " We offer a range of printing options to fit your specific needs, including digital printing, offset printing, and large format printing. Our team will help you choose the best printing method for your project based on your design, quantity, and budget.",
    img: "CatalogueDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const menuServicesList = [
  {
    number: "01",
    title: "Custom Design",
    desc: " We believe that every restaurant is unique, and that's why we offer custom Menu Design options for your menu. Our team of Menu Designers will work with you to create a design that reflects your brand's personality and effectively communicates your offerings to your customers.",
    img: "MenuDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Creative Concept",
    desc: " Our Graphic Designers will collaborate with you to develop a creative concept that showcases your menu items in a visually appealing and informative way. We'll take your ideas and bring them to life, creating a menu design that will leave a lasting impression on your customers.",
    img: "MenuDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Printing Options",
    desc: " We offer a range of printing options to suit your needs, including digital printing, offset printing, and large format printing. Our team will help you select the best printing method for your project based on factors such as design, quantity, and budget.",
    img: "MenuDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Fast Turnaround",
    desc: " We understand that time is critical when it comes to updating your menu. That's why we offer fast and reliable service, with a commitment to delivering your menu on time. You can focus on providing an excellent dining experience, while we take care of your menu design needs.",
    img: "MenuDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];

export const posterServicesList = [
  {
    number: "01",
    title: "Custom Design",
    desc: "Every company is different, which is why we provide poster design customization services. Our team of Poster Designers will collaborate with you to develop a look and feel that is representative of your company and clearly conveys what you have to offer to potential clients.",
    img: "PosterDesign/service-1",
    bgClass: "service_bg_1",
    sectionNo: "new_service_section-1",
  },
  {
    number: "02",
    title: "Creative Concept Development",
    desc: "Our Graphic Designers will work with you to brainstorm an original idea that will effectively present your business's goods and services. We'll use your suggestions to produce a poster layout that will attract more clients and distinguish you from the competition.",
    img: "PosterDesign/service-2",
    bgClass: "service_bg_2",
    sectionNo: "new_service_section-2",
  },
  {
    number: "03",
    title: "Printing Options",
    desc: "Digital printing, offset printing, and big format printing are just some of the printing services we provide. Based on design, quantity, and your budget, our staff can assist you in choosing the optimal printing process for your project.",
    img: "PosterDesign/service-3",
    bgClass: "service_bg_3",
    sectionNo: "new_service_section-3",
  },
  {
    number: "04",
    title: "Fast Turnaround Time",
    desc: "Time is of the essence when it comes to advertising your company, and we get that. That's why we guarantee timely delivery of your posters and provide rapid, dependable service. We will design your posters so that you can concentrate on offering first-rate goods and services.",
    img: "PosterDesign/service-4",
    bgClass: "service_bg_4",
    sectionNo: "new_service_section-4",
  },
];
